max_image_size: 2
max_attachment_size: 100

filters:
 - search
 - start_date
 - end_date
 - user_id
 - sales_id

user_filters:
  - name
  - team_id
  - role
  - user_type
  - status
  - email
  - role_toggle

fiber_product_codes:
  - DFB
  - GCL

unsupported_product_codes:
  - CEF
  - WDM
  - PPE
  - INT

dot_date_time: '%d.%m.%Y %H:%M'
dash_date: '%d-%b-%Y'
comma_date: '%d %b, %Y'
date: '%y%m%d'
pdf_date: '%d%m%Y'

fiber_bandwidths:
  - 10
  - 20
  - 30
  - 40
  - 50
  - 60
  - 70
  - 80
  - 100
  - 200
  - 250
  - 300
  - 500
  - 1000
  - 2000
  - 4000
  - 10000
  - 100000

alo_bandwidths:
  - 2
  - 4
  - 6
  - 8
  - 10
  - 20
  - 30
  - 50
  - 70
  - 100
  - 200
  - 500
  - 1000
  - 2000
  - 4000
  - 10000

de-ch: :de
fr-ch: :fr
it-ch: :it
de: :de
en: :en
fr: :fr
it: :it

