high_school: 0
diploma: 1
graduate: 2
post_graduate: 3
phd: 4

high_school_text: 'High School'
diploma_text: 'Diploma'
graduate_text: 'Gradudate'
post_graduate_text: 'Post Graduate'
phd_text: 'PHD'

university_per_day: 1.6
student_per_day: 0.5
