high_school: 0
diploma: 1
graduate: 2
post_graduate: 3
phd: 4

0_semester: 'Semester'
1_semester: 'Trimester'

0: 'High School Or Diploma'
1: 'High School Or Diploma'
2: 'Gradudate'
3: 'Post Graduate'
4: 'PHD'

1_status: 'Waiting Offer Letter'
2_status: 'Waiting SOP Submission'
3_status: 'Waiting COE'
4_status: 'Waiting Enrollment'
5_status: 'Enrollment Confirmed'
0_status: 'Application Rejected'


university_per_day: 1.6
student_per_day: 0.5

basic_uni_quarterly: 200
basic_uni_half_yearly: 350
basic_uni_yearly: 600

premium_uni_quarterly: 300
premium_uni_half_yearly: 550
premium_uni_yearly: 1000

basic_stud_quarterly: 15
basic_stud_half_yearly: 25
basic_stud_yearly: 40

premium_stud_quarterly: 25
premium_stud_half_yearly: 45
premium_stud_yearly: 80

basic_uni_quarterly_duration: 3
basic_uni_half_yearly_duration: 6
basic_uni_yearly_duration: 12

premium_uni_quarterly_duration: 3
premium_uni_half_yearly_duration: 6
premium_uni_yearly_duration: 12

basic_stud_quarterly_duration: 3
basic_stud_half_yearly_duration: 6
basic_stud_yearly_duration: 12

premium_stud_quarterly_duration: 3
premium_stud_half_yearly_duration: 6
premium_stud_yearly_duration: 12

basic_uni_quarterly_text: 'Basic Membership, Quarterly'
basic_uni_half_yearly_text: 'Basic Membership, Half Yearly'
basic_uni_yearly_text: 'Basic Membership, Yearly'

premium_uni_quarterly_text: 'Premium Membership, Quarterly'
premium_uni_half_yearly_text: 'Premium Membership, Half Yearly'
premium_uni_yearly_text: 'Premium Membership, Yearly'

basic_stud_quarterly_text: 'Basic Membership, Quarterly'
basic_stud_half_yearly_text: 'Basic Membership, Half Yearly'
basic_stud_yearly_text: 'Basic Membership, Yearly'

premium_stud_quarterly_text: 'Premium Membership, Quarterly'
premium_stud_half_yearly_text: 'Premium Membership, Half Yearly'
premium_stud_yearly_text: Premium Membership, Yearly'

