# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b9dd14db879561b9a543a7eb869b3efd7056266b264c7cbe4520ec4704c9989bcd19b046d0c021b8cce0d74ccee57c318e7b6771f43d89305e943c508b556fe
  jwt_secret: bbbca2ff4da2d095be4686adad84f8f9a07c361c038c9321b196f19189213cc0f6d2b8c38d3bd8bed2a1523f3ac53cb5862fbd643c8facf7827db8f86c2c28ff

test:
  secret_key_base: 55a49f4c3936d52f0e6aab5b49d6478c97fb961fc3a3cfa4e574c8d6cb0d0eec39ffd7e533fba64ae8f30d2e588a9927a3cf95494fe0633598fdbe01fb262952
  jwt_secret: bbbca2ff4da2d095be4686adad84f8f9a07c361c038c9321b196f19189213cc0f6d2b8c38d3bd8bed2a1523f3ac53cb5862fbd643c8facf7827dbdudewrotethislongtimeback

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>


